name: tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt-get install xvfb
    - run: npm i
    - run: xvfb-run --auto-servernum npm test
    - name: Cleanup xvfb pidx
      uses: bcomnes/cleanup-xvfb@v1
